production: &default
  adapter: postgresql
  encoding: unicode
  database: neurones_production
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: neurones_development

test:
  <<: *default
  database: neurones_test
